### ISSUE TITLE
data_large.lines format

### ISSUE THREAD

**Issue by dragoon** [cmichi/gtfs-visualizations#3]
Hello, could you please briefly explain the format of the `data_large.lines` file?
I'm not sure why with shapes.txt of only 70Mb the data_large.lines is about 3Gb.

**Comment by cmichi** [comment]
Ah yeah, there is a lot of room for optimization there and the format is by far ideal, but I'm no longer actively working on the project. It's been a while and I just had to look it up as well: https://github.com/cmichi/gtfs-visualizations/blob/master/render.js#L289. Each line contains the number of trips, the type of a route and a concatenated list of coordinates along the route.
